# Define input variables for the Terraform configuration.

# variable "region" {
#   type    = string
#   default = "ap-south-1"
# }

variable "env_name" {
  type    = string
  default = "prod"  # Please only use plain space less text,  don't use capital letters, -, _, or any other symbols in the environment name
  description = "The environment name"
}
variable "global_prefix" {
  type = string
  default = "lkh"
  description = "The global prefix"
}

locals {
  ec2_key_name         = "${var.global_prefix}-${var.env_name}-terraform-key"
  ec2_access_role_name = "${var.global_prefix}-${var.env_name}-ec2-iam-role"
  alb_name             = "${var.global_prefix}-${var.env_name}-alb"
}

# variable "ec2_key_name" {
#   type        = string
#   default     = local.ec2_key_name
#   description = "Key-pair generated by Terraform"
# }

variable "instance_type" {
  type    = string
  default = "c5a.large"
  description = "The instance type"
}

# variable "ec2_access_role_name" {
#   type    = string
#   default = local.ec2_access_role_name
#   description = "The name of the IAM role for EC2 access"
# }

variable "ami" {
  type    = string
  default = "ami-062e41c7393aca165"
  description = "The AMI ID"
}

variable "root_block_device_volume_size" {
  type    = number
  default = 100
  description = "The root block device volume size"
}

variable "vpc_cidr_block" {
  type    = string
  default = "10.0.0.0/16"
  description = "The VPC CIDR block"
}

variable "private_subnet_cidr_blocks" {
  type    = list(string)
  default = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
  description = "The private subnet CIDR blocks"
}
variable "public_subnet_cidr_blocks" {
  type    = list(string)
  default = ["10.0.101.0/24", "10.0.102.0/24", "10.0.103.0/24"]
  description = "The public subnet CIDR blocks"
}
variable "availability_zones" {
  type    = list(string)
  # default = ["ap-south-1a", "ap-south-1b", "ap-south-1c"]
  default = ["eu-west-1a", "eu-west-1b", "eu-west-1c"]
  description = "The availability zones"
}

# variable "alb_name" {
#   type    = string
#   default = local.alb_name
#   description = "The name of the ALB - Application Load Balancer"
# }

# ACM Certificate Domain Name
variable "acm_domain_name" {
  description = "The domain name for which the certificate should be issued."
  type        = string
  default     = "*.example.com" # Change this to your domain name
}

# ACM Certificate Domain Zone
variable "acm_domain_zone" {
  description = "The domain zone for which the certificate should be issued."
  type        = string
  default     = "example.com" # Change this to your domain zone
}

# Load Balancer and tg variables
variable "target_groups" {
  type = list(object({
    name          = string
    instance_port = number
    path_patterns = list(string)
    host          = string
    lb_port       = number
    priority      = number
  }))
  default = [
    {
      name          = "f-login"
      instance_port = 4101
      path_patterns = ["/signin", "/signup"]
      host          = "example.com"
      lb_port       = 80
      priority      = 1
    },
    {
      name          = "upload-api"
      instance_port = 4113
      path_patterns = []
      host          = "upload.example.com"
      lb_port       = 80
      priority      = 16
    }
  ]
}
